services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
  fast-api:
    build: ./backend/
    volumes:
      - ./backend/.dockervenv:/src/.venv
      - ./backend:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'blog'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  react_node_modules:
  mysql_data:

